name = "SiennaNEM"
uuid = "2b2140f2-b9c0-4054-8dfe-2e6bd74cbbbe"
authors = ["Muhammad Yasirroni <yasirroni@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
HydroPowerSimulations = "fc1677e0-6ad7-4515-bf3a-bd6bf20a0b1b"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerSimulations = "e690365d-45e2-57bb-ac84-44ba829e73c4"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
StorageSystemsSimulations = "e2f1a126-19d0-4674-9252-42b2384f8e3c"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
Dates = "1.11.0"
HiGHS = "1.19.0"
HydroPowerSimulations = "0.11.1"
PowerModels = "0.21.5"
PowerSimulations = "0.30.2"
PowerSystems = "4.6.2"
StorageSystemsSimulations = "0.12.0"
TimeSeries = "0.24.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
