name = "SiennaNEM"
uuid = "2b2140f2-b9c0-4054-8dfe-2e6bd74cbbbe"
authors = ["Muhammad Yasirroni <yasirroni@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
