name = "SiennaNEM"
uuid = "2b2140f2-b9c0-4054-8dfe-2e6bd74cbbbe"
authors = ["Muhammad Yasirroni <yasirroni@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
HydroPowerSimulations = "fc1677e0-6ad7-4515-bf3a-bd6bf20a0b1b"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerAnalytics = "56ce1300-00bc-47e4-ba8c-b166ccc19f51"
PowerGraphics = "5f7eddb3-86b1-49e8-a95a-ddc0f45eea41"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerSimulations = "e690365d-45e2-57bb-ac84-44ba829e73c4"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
StorageSystemsSimulations = "e2f1a126-19d0-4674-9252-42b2384f8e3c"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
Arrow = "2.8.0"
CSV = "0.10.15"
DataFrames = "1.7.0"
Dates = "1.11.0"
HiGHS = "1.19.0"
HydroPowerSimulations = "0.11.1"
InfrastructureSystems = "2.6.0"
Logging = "1.11.0"
OrderedCollections = "1.8.1"
PlotlyJS = "0.18.17"
Plots = "1.40.19"
PowerAnalytics = "1.0.2"
PowerGraphics = "0.20.0"
PowerModels = "0.21.5"
PowerSimulations = "0.30.2"
PowerSystems = "4.6.2"
StorageSystemsSimulations = "0.12.0"
TimeSeries = "0.24.2"
julia = "1.11"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "PrettyTables", "Revise", "Test"]
